#!/bin/zsh

#
# Copyright 2022-2025 Creek Contributors (https://github.com/creek-service)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Clone Creek repos.
# Parameters:
#  1 - the directory to output to. Default: current dir
#  2 - repos to exclude, space-seperated

OUTPUT_DIR=${1:-.}
EXCLUDED=("${(@s: :)2:-}")

if ! REPOS=($(gh repo list creek-service --limit 2000 --no-archived --json=name --jq '.[].name'));
then
  return 1
fi

for repo_name in $REPOS
do
  if (( EXCLUDED[(Ie)$repo_name] != 0 )); then
    continue;
  fi

  (cd $OUTPUT_DIR && git clone git@github.com:creek-service/$repo_name.git)
done
