#!/bin/zsh

#
# Copyright 2022-2023 Creek Contributors (https://github.com/creek-service)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# diff a single repo, including looking for untracked files.

if ! git_status_output="$(git status --porcelain)";
then
  # `git status` had an error
  echo "'git status' failed in. Exit code: $?"
  return 1
elif [ "$git_status_output" != "" ]; then
  # Working directory has uncommitted changes.
  echo "$git_status_output" | grep "??"
  git --no-pager diff --minimal "$@"
fi

