#!/bin/zsh

#
# Copyright 2022-2025 Creek Contributors (https://github.com/creek-service)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# If the file passed in the file arg exists, execute the command passed in the subsequent commands
# For example run `_creek_if_file ".github/workflows/version.yml" /gradlew cV -quiet`.

if [ "$#" = "0" ]; then
	echo "$0 <file to check> <commands to run if file exists...>"
	exit 1
fi

FILE=$1
shift

if [[ -f "$FILE" ]]; then
    "$@"
fi
