#!/bin/zsh

#
# Copyright 2022 Creek Contributors (https://github.com/creek-service)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# List diffs for all local Creek git repos. Pass --name-only to only list names
# Return codes:
#  0: no changes found in any local Creek repo
#  1: changes found in at least one local Creek repo
#  2: error running git status command

readonly BASE_DIR=${CREEK_BASE_DIR:?"CREEK_BASE_DIR not set. Set this to the root of your local Creek git repos."}

local return_code=0
for repo in $BASE_DIR/creek-*
do
  if ! local git_status_output="$(cd $repo && git status --porcelain)"; then
      # `git status` had an error
      echo "'git status' failed in $repo: $?"
      return 2
  elif [ "$git_status_output" = "" ]; then
      # Working directory is clean
  else
      # Working directory has uncommitted changes.
      echo ----- $(basename $repo) -------------------
      echo $(echo $git_status_output | grep "??")
      (cd $repo && git --no-pager diff "$@")
      return_code=1
  fi
done

return $return_code


