#!/bin/zsh

#
# Copyright 2022-2023 Creek Contributors (https://github.com/creek-service)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Run the supplied command in each local Creek repo that is released as part of Creek
# For example run `creek_released_each ./gradlew cV -quiet` to output the current version of each repo.

CREEK_EACH_EXCLUDE="creek-release-test multi-module-template single-module-template" creek_git_each _creek_if_file ".github/release.yml" "$@"