#!/bin/zsh

#
# Copyright 2022 Creek Contributors (https://github.com/creek-service)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Determines the base dir for Creek repos.
# This to the parent directory of the script repos.
# But can be overridden by setting the CREEK_BASE_DIR env var.

if [[ -z $CREEK_BASE_DIR ]];
then
  echo "CREEK_BASE_DIR not set. Please set CREEK_BASE_DIR and try again" >&2
  return 1
fi

echo "$CREEK_BASE_DIR"
