#!/bin/zsh

#
# Copyright 2022-2025 Creek Contributors (https://github.com/creek-service)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Run the supplied command in each local Creek repo that utilises Gradle as a build tool
# For example run `creek_gradle_each ./gradlew cV -quiet` to output the current version of each repo.
# For example run `creek_gradle_each "gradle wrapper --gradle-version 8.0.2"` to update all gradle projects to a new version of Gradle

creek_git_each _creek_if_file "gradlew" "$@"